### PR TITLE
Easy application of decorators to Bindings

### PR DESCRIPTION
**Pull request by AlexejStukov**
Using the same approach as for class based consumers, so you can just set ``<decorator-name> = True`` for the class to get the decorator.

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Binding already has its own user code?

**Comment by AlexejStukov** [comment]
I had problems getting the right user in ``has_permission``. After some searching around in the code and finding out, that i have to decorate the consumer-method, I thought it might be a good idea to go with the same approach as the consumers. Seems just easier for me.

**Comment by andrewgodwin** [comment]
Well, this still doesn't handle user porting on `websocket.connect`, so I'm wary about adding it in here, that's the thing. I'd rather it was handled in the Demultiplexer, really.

**Comment by AlexejStukov** [comment]
Then you would have to serialize and deserialize the user and session. Wouldn't that be a problem, if there is a custom user model?

**Comment by andrewgodwin** [comment]
Err, why? I'm saying we just have people set `http_user` on the Demultiplexer, which automatically will do the session porting and set `message.user`, and then the existing code will pick it up. I don't see how this proposed method is better.

**Comment by AlexejStukov** [comment]
But I would still need to decorate the ``consumer``-method of the binding with ``channel_session_user`` or ``channel_session``, since the Demultiplexer just sends the payload of the message.

**Comment by andrewgodwin** [comment]
The `Demultiplexer` should absolutely annotate `message.user` if it has `http_user` set, so there is no need to add the decorator again on the binding. If it's not getting message.user that's a bug, maybe related to #280.

**Comment by AlexejStukov** [comment]
``http_user`` is set and I get a message without user and session in the bindings ``consumer``/``trigger_inbound``-methods. I don't know if it's related to #280. Thought it is necessary to add the decorator to the bindings ``consumer``-function, since it's also required for normal consumer-functions like in this example from the docs:
````python
# Connected to websocket.connect
@channel_session_user_from_http
def ws_add(message):
    # Add them to the right group
    Group("chat-%s" % message.user.username[0]).add(message.reply_channel)

# Connected to websocket.receive
@channel_session_user
def ws_message(message):
    Group("chat-%s" % message.user.username[0]).send({
        "text": message['text'],
    })

# Connected to websocket.disconnect
@channel_session_user
def ws_disconnect(message):
    Group("chat-%s" % message.user.username[0]).discard(message.reply_channel)
````
Closing this for now.

**Comment by andrewgodwin** [comment]
Ah! Yes, the demultiplexer currently forwards the message to a channel rather than using local routing in order to serve it, so it loses `.user` and `.session` in that process. Hrm.

**Comment by andrewgodwin** [comment]
It's easy to use the routing directly instead and preserve the attributes, but it meant that workers wouldn't obey channel restrictions correctly (workers listening with a demultiplexer would service all handling channels too), but I think that's fine as it makes the whole thing more efficient anyway.

**Comment by andrewgodwin** [comment]
But, then again, the message generated by the demultiplexer has different content and I'd have to special case things like `.user` in order to preserve them, which I don't like.

**Comment by AlexejStukov** [comment]
I also don't think it's a good Idea to approach the relationship between ``demultiplexer`` and ``binding`` any different, than between function-based consumers like the one in the example above. Thanks again!

**Pull request merged**
