### PR TITLE
Highlight code examples

### PR DESCRIPTION
**Pull request by andreif**

### CODE REVIEW

**Comment by andreif** [comment]
Oops, something happened, give me few minutes to find the problem

**Comment by andreif** [comment]
Done. I've tested `highlight` and it worked well for one block, but then after changing all of them, code disappeared :/

**Comment by andreif** [comment]
Why not?

**Comment by andrewgodwin** [comment]
Ah, sorry, I must have closed rather than merged! I've reopened but the docs have changed a lot since, so if you want to update it feel free, or I'll get to it eventually.

**Comment by andreif** [comment]
Aha, I see. I will update it

**Comment by andrewgodwin** [comment]
Closing for now, outdated.

**Pull request closed without merging**
