### PR TITLE
Added in reporting data and documentation for loadtesting

### PR DESCRIPTION
**Pull request by raiderrobert**

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Looks like you have the same content in the main dir and the subdir - is this intentional?

**Comment by raiderrobert** [comment]
@andrewgodwin yep, it was intentional, as I thought that's what you asked for. Would you prefer the main dir make reference to the subdir thru a link instead?

**Comment by andrewgodwin** [comment]
Yes please, I'd rather have a sort of index with date links up there. Sorry for not making that clearer!

**Comment by raiderrobert** [comment]
@andrewgodwin done

**Comment by andrewgodwin** [comment]
Thanks!

**Pull request merged**
