### PR TITLE
Added "callbacks" to binding

### PR DESCRIPTION
**Pull request by AlexejStukov**
If the user sends a message with a ``cb_id``, the binding will answer with the same ``cb_id`` and a status (and optionally other details).

### CODE REVIEW

**Comment by andrewgodwin** [comment]
Is the idea here to notify the user when an action has been completed? Surely this is done by receiving the relevant outgoing binding update - I don't really want to add something like this in.

**Comment by AlexejStukov** [comment]
That's right for update and delete, but if the user creates an object, there is no way of telling if the incomming create message is caused by the users action or by somebody else, since the pk is unknown.

**Comment by andrewgodwin** [comment]
True, but I still don't want to add something like this to the default bindings - this is the sort of think I would imagine being put in a third-party app as it's getting more and more opinionated.

**Comment by AlexejStukov** [comment]
Ok, then I'll close this. Thanks for your time, anyway :+1:

**Pull request closed without merging**
