### PR TITLE
PEP8

### PR DESCRIPTION
**Pull request by ricomoss**
Updating for PEP8 standards.  Using the .format() string built-in over the %s style.  Also, removed unused imports.

No functional changes were made in this pull request.  This "clean up" was made while reviewing the source code to see where I can contribute.

### CODE REVIEW

**Comment by andrewgodwin** [comment]
I hate to be a downer, but like Django I don't follow the 80-character lines part of PEP8, so I'm not going to accept this with all the line break changes - it makes the code a lot harder to read.

If you want to undo the line breaks but keep .format() etc, I'll happily merge those.

**Comment by ricomoss** [comment]
I'll undo the 80-character breaks (although I strongly disagree :P).

I'd love to see this project get to 1.0 as quickly as possible.  Please let me know if there is anything you'd like me to work on (functionally).  I've got a few months of free time and this project is now my number 1 priority.  :)  rico.cordova at gmail.com

**Comment by bastianh** [comment]
I guess the code should follow the django coding style (https://docs.djangoproject.com/en/1.9/internals/contributing/writing-code/coding-style/)

I don't think replacing the format() stuff is necessary ( since under python3 the % operator for strings is twice as fast ) and it's not deprecated.

**Comment by andrewgodwin** [comment]
Closing for now, outdated - reopen if you get to a new version.

**Pull request closed without merging**
